server:
  port: 8080
spring:
  datasource:
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
  output:
    ansi:
      enabled: always

indexing-settings:
  sites:
    - url: https://skillbox.ru
      name: Skillbox
    - url: https://playback.ru
      name: Playback
    - url: https://mpei.ru
      name: Национальный исследовательский университет МЭИ
    - url: https://ipfran.ru
      name: Институт прикладной физики РАН
    - url: https://www.svetlovka.ru
      name: ЦГМБ имени М.А.Светлова

jsoup-setting:
  userAgent: KapibaraSearchBot
  referrer: http://www.google.com
  timeout: 120_000
  pauseBeforeParseMultiplier: 15_000
  pauseBeforeParseSummand: 1_000
  maxBodySize: 0
  ignoreContentType: true